// The one-line explanations behind every settings "?" — shared by the Settings drawer and by the
// popovers that carry a setting into the place it applies (the model picker's agent settings, the
// GitHub picker's prompt). One table, so a setting reads the same wherever it is surfaced.
export const SETTINGS_HELP = {
  permissionMode: "The permission mode new Claude Code threads launch with. Auto runs safe actions and asks you to approve the risky ones in the thread. Bypass launches the worker with --dangerously-skip-permissions: it never asks, so nothing waits on you and nothing is checked either. Takes effect on the next thread you dispatch; to change a thread that already exists, use the picker beside its model in the prompt box. Codex threads always run with full workspace access and are unaffected.",
  promptCacheTtl: "Which prompt-cache tier a new Claude thread writes to. A 1-hour entry costs twice the input price to write, a 5-minute entry 1.25 times; the hour only pays off when the thread's cache actually survives that long. Measured 2026-09-03: cache writes were half of a day's spend and the entries were lost every 15 to 30 minutes regardless, so 5 minutes was the cheaper tier. Automatic leaves the choice to Claude Code, which picks 1 hour on a subscription. Takes effect on the next thread you dispatch and on a thread that resumes after its worker exited.",
  appearance: "Applies to this browser across all projects. System follows the device appearance.",
  localFileOpener: "Chooses how a local file Frizz can't show itself opens — a PDF, a spreadsheet, an archive. Pictures open in Frizz's own viewer, and Markdown, code and other text files in its reader; each carries an Open action that uses this setting (a picture's always goes to the OS default viewer). $EDITOR runs the editor your shell names in $VISUAL or $EDITOR — a GUI one such as code, zed or subl; a terminal editor like vim cannot open outside a terminal.",
  density: "How much of a diff shows before you ask for it, in this browser. Compact collapses every diff to its header row (click one to open it); Comfortable shows them in full. Applies immediately.",
  queueOrder: "Orders the Needs-you queue and the sidebar's rested threads by when each entered the queue. Oldest first (FIFO, default) surfaces the longest-waiting item first, so you cycle through everything; Newest first (LIFO) puts the newest on top. The order is set when the page draws the queue: while it is open, a new arrival always joins the bottom, in either order, so nothing moves the card you are reading. Applies immediately in this browser.",
  notifications: "Shows a desktop notification when work needs attention while this window is hidden.",
  homeFolder: "Where threads started in Home run. Home is the prompt box's choice for work that belongs to no project yet — cloning a repository, a question about this machine. Blank is your home folder, and ~ is expanded. A registered project's own folder cannot be used; start those threads in the project. Takes effect on the next thread started in Home, and on a Home thread when it next resumes.",
  projectRail: "Shows a column of every project on this machine down the left edge; clicking a project's square focuses the page on it. Off by default: the page shows one project at a time, and a standing list of the others is an easy way to leave the one you were in. With it off, the project switcher at the top of the queue does the same, and also offers All projects.",
  projectInstructions: "Instructions every agent in this project follows, Claude Code and Codex alike. They are the project's FRIZZ.md: saved to the repo root, where they can be committed and reviewed, and injected into each worker's system prompt. Takes effect on the next thread you dispatch and on any thread when it next resumes.",
  githubPrompt: "The prompt for every item dispatched from the GitHub picker, issues and PRs alike. The default has the worker read the whole thread, classify it, and branch — reproduce + fix-plan for a bug, a plan for a feature, an adversarial review for a PR.",
} as const
