import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";
import { WORKER_PLUGIN_REQUIRED_FILES } from "./worker-plugin-closure.ts";

/**
 * The published package is the REPO ROOT, so `files` is the only thing standing between npm and the
 * whole checkout — `plans/`, `attachments/`, `scratch/`, `.frizz/`, agent scratch directories, every worktree
 * under `.claude/`. When the package lived in `packages/cli` a mistake here shipped a few stray files;
 * now it can ship the repository. npm excludes `.git` and `node_modules` on its own and nothing else.
 *
 * These assertions are deliberately about the MANIFEST rather than a real `npm pack`: packing runs the
 * full prepack build (web bundle included), which is far too slow for the unit suite. What they catch
 * is the realistic regression — someone widening `files` — not a packing engine bug.
 */
const manifest = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "package.json"), "utf8")
) as { files?: string[]; bin?: Record<string, string>; name?: string; frizzServer?: unknown; dependencies?: Record<string, string> };
const serverManifest = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "packages", "server-release", "package.json"), "utf8")
) as { files?: string[]; name?: string; frizzServer?: unknown; dependencies?: Record<string, string>; engines?: { node?: string }; pnpm?: { onlyBuiltDependencies?: string[] } };
const sourceServerManifest = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "packages", "server", "package.json"), "utf8")
) as { dependencies?: Record<string, string> };

/** Build outputs only. Every entry is regenerated by prepack and none is checked in. */
const SHELL_PUBLISHED_PATHS = ["dist"];
const SERVER_PUBLISHED_PATHS = ["dist", "web-dist", "runtime"];

test("the published package ships only build output, never repository content", () => {
  assert.deepEqual(manifest.files, SHELL_PUBLISHED_PATHS);
  assert.deepEqual(serverManifest.files, SERVER_PUBLISHED_PATHS);
});

test("no files entry can escape the package root or widen to the whole checkout", () => {
  for (const entry of [...(manifest.files ?? []), ...(serverManifest.files ?? [])]) {
    assert.ok(!entry.startsWith("/"), `absolute files entry: ${entry}`);
    assert.ok(!entry.includes(".."), `files entry escapes the package root: ${entry}`);
    assert.ok(
      !["*", ".", "./", "**", "**/*"].includes(entry),
      `files entry publishes the entire checkout: ${entry}`
    );
  }
});

/**
 * `runtime/` is a COPY of `board/` and `cc-worker/`, so the closure the pack step asserts is only as
 * good as those source paths still existing. Renaming a required hook is otherwise caught by nothing
 * until prepack — or, for the frizz-dev path, until a promoted artifact fails to verify.
 */
test("every required worker-plugin file exists at the repo root the staged runtime mirrors", () => {
  const repo = join(import.meta.dirname, "..");
  assert.ok(WORKER_PLUGIN_REQUIRED_FILES.length > 0);
  for (const file of WORKER_PLUGIN_REQUIRED_FILES) {
    assert.ok(existsSync(join(repo, file)), `required worker-plugin file is missing from source: ${file}`);
  }
});

test("every bin target resolves inside a published directory", () => {
  const bins = Object.values(manifest.bin ?? {});
  assert.ok(bins.length > 0, "the package must expose a bin");
  for (const target of bins) {
    const normalized = target.replace(/^\.\//, "");
    assert.ok(
      SHELL_PUBLISHED_PATHS.some((dir) => normalized.startsWith(`${dir}/`)),
      `bin ${target} is not inside a published directory, so the installed CLI would be missing`
    );
  }
});

test("the shell bootstraps the versioned public server contract", () => {
  assert.deepEqual(manifest.frizzServer, {
    package: "frizz-server",
    version: "0.15.8",
    protocol: 1,
    dataEpoch: 1,
  });
  assert.equal(serverManifest.name, "frizz-server");
  assert.deepEqual(serverManifest.frizzServer, { protocol: 1, dataEpoch: 1 });
});

test("native server dependencies do not leak back into the stable shell", () => {
  // The shell stays addon-free: it is what `npx frizz` installs first, on any box.
  assert.equal(manifest.dependencies?.["node-pty"], undefined);
  // The server's one pty is a THREAD TERMINAL (server/src/thread-terminals.ts), and it is loaded LAZILY —
  // on a terminal's start, never at boot — so a box where the addon will not load still serves every
  // project and the terminal pane says why. Pinned to the beta that ships glibc Linux prebuilds (node-pty
  // 1.1 had none, which is how #42 killed every Linux boot), in the published server and the source alike.
  // No `onlyBuiltDependencies` entry: the generation installs with --ignore-scripts and node-pty loads its
  // prebuild directly, so no install script (and no `node-gyp rebuild` fallback) ever runs.
  assert.equal(serverManifest.dependencies?.["node-pty"], "1.2.0-beta.15");
  assert.equal(sourceServerManifest.dependencies?.["node-pty"], "1.2.0-beta.15");
  assert.deepEqual(serverManifest.pnpm?.onlyBuiltDependencies, ["@parcel/watcher"]);
  assert.equal(serverManifest.dependencies?.["@parcel/watcher"], "^2.5");
});

test("server packages declare their actual runtime contracts", () => {
  assert.equal(serverManifest.engines?.node, "^22.13.0 || >=23.4.0");
  assert.equal(sourceServerManifest.dependencies?.["qrcode-generator"], "^2.0.4");
  assert.equal(serverManifest.dependencies?.["qrcode-generator"], undefined, "the public bundle embeds QR rendering");
});
